name: CameraApp
options:
  bundleIdPrefix: com.example
targets:
  CameraApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: CameraApp
    resources:
      - path: assets/frame.jpg
    info:
      path: CameraApp/Info.plist
      properties:
        UIStatusBarHidden: true
        UIViewControllerBasedStatusBarAppearance: false
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationLandscapeRight
          - UIInterfaceOrientationLandscapeLeft
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationLandscapeRight
          - UIInterfaceOrientationLandscapeLeft
        NSCameraUsageDescription: "Potrzebujemy dostepu do kamery do robienia zdjec."
        NSPhotoLibraryAddUsageDescription: "Potrzebujemy zapisywac zdjecia w galerii."
        NSPhotoLibraryUsageDescription: "Potrzebujemy zapisywac zdjecia w galerii."
